import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const backgroundStyle: React.CSSProperties = {
    backgroundImage: "url('/DarkEmptyRoom.jpg')", // Replace with the actual path
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    position: "fixed", // Ensures the background remains in place while scrolling
    top: 0,
    left: 0,
    height: "100vh",
    width: "100vw",
    zIndex: -1, // Keeps it behind other content
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div style={backgroundStyle}></div>
        {children}
      </body>
    </html>
  );
}
